sudo: false
language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
    - tools
env:
  global:
    - ANDROIDHOME=${ANDROID_HOME}
    - ANDROIDSDK=${ANDROID_HOME}
  matrix:
    - ABI=armeabi-v7a
    - ABI=arm64-v8a
install:
  - echo y | sdkmanager "ndk-bundle"
script:
  - echo "ABI=${ABI}"
  - cd example && sh ../android-env.sh make
