sudo: false
language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
env:
  matrix:
    - ABI=armeabi-v7a
    - ABI=arm64-v8a
script:
  - echo "ABI=${ABI}"
  - cd example && sh ../android-env.sh make
